name = "GeomOpt"
uuid = "ca147568-c688-4a55-a13d-dbd284330f4b"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.0.1-dev"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
